site_name: Mcliba
nav:
  - Home: index.md
  - Котятки: md_files/theory/fgbhn.md
  - Тут будет про вопросы на собесах :
    - 'Behavioral-интервью(1-26) и примеры задач на интервью(27-41)': 20.md
    - 'Общие вопросы 1-49': 23.md
    - 'Общие вопросы 51-100': 21.md
    - 'Углубленные вопросы': 22.md
  - Теория БД:
    - 'Data Lake и Data Warehouse, хранилища: EDW, виртуальное, облачное; примеры бд': md_files/theory/DWH.md
    - 'SCD, версионность, история': 1.md
    - 'SMP и MPP-архитектуры. Гибридная архитектура (NUMA)': poo.md
    - 'Архитектуры баз, проектирование, физ. реализация': 3.md
    - 'Виды БД, СУБД': 2.md
    - 'Индексы': 4.md
    - 'Ключи':
      - fff: fff.md
    - 'Копирование и восстановление данных. Репликация': 5.md
    - 'Курсоры': 6.md
    - 'Масштабирование: шардирование, партиционирование, репликация': 7.md
    - 'Модель сущность-связь': 8.md
    - 'Нормальные формы, нормализация, денормализация':
      - fff: 9.md
    - 'Оконные функции': md_files/theory/10.md
    - 'Оптимизация, планировщик': 11.md
    - 'Партиционирование, дистрибуция (pg)': md_files/theory/12.md
    - 'Представления, CTE, Секционированные таблицы': 13.md
    - 'Транзакции, блокировки': md_files/theory/14.md
    - 'Триггеры, функции':
      - fff: 15.md


markdown_extensions:
  - attr_list
  - md_in_html

theme:
  name: material
  features:
    - navigation.tabs
    #- navigation.instant
   # - navigation.prune
    - navigation.top
  nav_style: default

#     [![With sections][8]][8]
  #  - navigation.expand #раскрывает вкладыши меню